// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:ffi_jpeg_encode/ffi_jpeg_encode.dart')
library;

import 'dart:ffi' as ffi;

/// Encodes JPEG to memory buffer. Returns result with data pointer and size.
/// On failure, result.data will be NULL and result.size will be 0.
/// Caller MUST call jo_free_buffer(result.data) when done.
///
/// subsample_mode: JO_SUBSAMPLE_AUTO (-1), JO_SUBSAMPLE_444 (0), or JO_SUBSAMPLE_420 (1)
@ffi.Native<
  JpegEncodeResult Function(
    ffi.Pointer<ffi.Char>,
    ffi.Int,
    ffi.Int,
    ffi.Int,
    ffi.Int,
    ffi.Int,
  )
>()
external JpegEncodeResult jo_encode_jpg_to_mem(
  ffi.Pointer<ffi.Char> data,
  int width,
  int height,
  int comp,
  int quality,
  int subsample_mode,
);

/// Frees a buffer allocated by jo_encode_jpg_to_mem
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.UnsignedChar>)>()
external void jo_free_buffer(ffi.Pointer<ffi.UnsignedChar> buffer);

/// Memory buffer result structure
final class JpegEncodeResult extends ffi.Struct {
  /// Pointer to JPEG data (caller must free with jo_free_buffer)
  external ffi.Pointer<ffi.UnsignedChar> data;

  /// Size of the JPEG data in bytes
  @ffi.Size()
  external int size;
}

const int JO_SUBSAMPLE_AUTO = -1;

const int JO_SUBSAMPLE_444 = 0;

const int JO_SUBSAMPLE_420 = 1;
